universe = container
# If you rebuild and push the image to docker hub, this can just be:
# docker_image = organization/image_name
docker_image = docker://hliu794/llms_for_assertions:1749626215

# These should be adjusted based on the actual needs of the workflow
request_disk = 60GB
request_memory = 24GB
request_cpus = 1
request_gpus = 1
# You're prioritized on a specific machine, but if you ever want to scale to
# the wider pool, these can be used to target specific GPU models and memory
# gpus_minimum_capability = 7.5
gpus_minimum_memory = 12288

# We will be running a bash script that will unzip data and set up the environment as needed.
executable = /bin/bash
transfer_executable = false
arguments = run_chtc.sh

# Any other files that need to be moved from the AP to the remote machine can be listed here.
transfer_input_files = file:///staging/hliu794/models/deepseek-coder-6.7b-instructD/, run_chtc.sh

# HTCondor will bring back any changed file in the sandbox. Uncomment and add
# specific files (or directories) to limit the returned output
#transfer_output_files = output,my_output.txt,
transfer_output_files = results_nl

# Save the stdout, stderr, and htcondor logs
output = $(CLUSTERID).out
error = $(CLUSTERID).err
log = metl.log

+WantGPULab = true

queue